-- MySQL Script generated by MySQL Workbench
-- Sat Oct 30 14:07:21 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BloodDonationSystemDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `BloodDonationSystemDB` ;

-- -----------------------------------------------------
-- Schema BloodDonationSystemDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BloodDonationSystemDB` DEFAULT CHARACTER SET utf8 ;
USE `BloodDonationSystemDB` ;

-- -----------------------------------------------------
-- Table `BloodDonationSystemDB`.`BloodBank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationSystemDB`.`BloodBank` ;

CREATE TABLE IF NOT EXISTS `BloodDonationSystemDB`.`BloodBank` (
  `blood_bank_id` INT(5) NOT NULL,
  `monitoring_process` INT(5) NOT NULL,
  `manager` INT(5) NOT NULL,
  `address` VARCHAR(60) NOT NULL,
  `donor_record` INT(5) NULL,
  `donor` INT(5) NULL,
  `hospital` INT(5) NULL,
  `name` VARCHAR(60) NOT NULL,
  `total_donations` INT NULL DEFAULT 0,
  PRIMARY KEY (`blood_bank_id`),
  UNIQUE INDEX `donors_UNIQUE` (`donor` ASC) VISIBLE,
  UNIQUE INDEX `donor_record_UNIQUE` (`donor_record` ASC) VISIBLE,
  UNIQUE INDEX `manager_UNIQUE` (`manager` ASC) VISIBLE,
  UNIQUE INDEX `monitoring_process_UNIQUE` (`monitoring_process` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationSystemDB`.`BloodType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationSystemDB`.`BloodType` ;

CREATE TABLE IF NOT EXISTS `BloodDonationSystemDB`.`BloodType` (
  `blood_type_id` INT NOT NULL,
  `o_type_blood_type` TINYINT(1) NULL,
  `a_type_blood_type` TINYINT(1) NULL,
  `b_type_blood_type` TINYINT(1) NULL,
  `a_b_type_blood_type` TINYINT(1) NULL,
  PRIMARY KEY (`blood_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationSystemDB`.`Donor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationSystemDB`.`Donor` ;

CREATE TABLE IF NOT EXISTS `BloodDonationSystemDB`.`Donor` (
  `donor_id` INT(5) NOT NULL,
  `blood_bank` INT(5) NULL,
  `notification_blood_bank` INT(5) NULL,
  `blood_result` INT(5) NOT NULL,
  `donor_record` INT(5) NULL,
  PRIMARY KEY (`donor_id`),
  UNIQUE INDEX `blood_result_UNIQUE` (`blood_result` ASC) VISIBLE,
  UNIQUE INDEX `donor_record_UNIQUE` (`donor_record` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationSystemDB`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationSystemDB`.`Address` ;

CREATE TABLE IF NOT EXISTS `BloodDonationSystemDB`.`Address` (
  `address_id` VARCHAR(60) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `zip_code` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationSystemDB`.`BloodResult`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationSystemDB`.`BloodResult` ;

CREATE TABLE IF NOT EXISTS `BloodDonationSystemDB`.`BloodResult` (
  `blood_result_id` INT(5) NOT NULL,
  `positive_result` INT(5) NULL,
  `negative_result` INT(5) NULL,
  `transfusion_doctor` INT(5) NULL,
  `laboratory` INT(5) NULL,
  PRIMARY KEY (`blood_result_id`),
  UNIQUE INDEX `positive_result_UNIQUE` (`positive_result` ASC) VISIBLE,
  UNIQUE INDEX `negative_result_UNIQUE` (`negative_result` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationSystemDB`.`DiseaseVerification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationSystemDB`.`DiseaseVerification` ;

CREATE TABLE IF NOT EXISTS `BloodDonationSystemDB`.`DiseaseVerification` (
  `disease_verification_id` INT(5) NOT NULL,
  `laboratory` INT(5) NOT NULL,
  `donor_record` INT(5) NULL,
  `disease_description` VARCHAR(60) NOT NULL,
  `disease_result` INT NULL DEFAULT 0,
  PRIMARY KEY (`disease_verification_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationSystemDB`.`DonorRecord`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationSystemDB`.`DonorRecord` ;

CREATE TABLE IF NOT EXISTS `BloodDonationSystemDB`.`DonorRecord` (
  `donor_record_id` INT(5) NOT NULL,
  `donor` INT(5) NOT NULL,
  `blood_type` INT(5) NOT NULL,
  `blood_bank` INT(5) NOT NULL,
  `blood_result` INT(5) NULL,
  `disease_verification` INT(5) NOT NULL,
  `address` VARCHAR(60) NULL,
  `full_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`donor_record_id`, `blood_type`, `blood_bank`),
  UNIQUE INDEX `donor_UNIQUE` (`donor` ASC) VISIBLE,
  UNIQUE INDEX `disease_verification_UNIQUE` (`disease_verification` ASC) VISIBLE,
  UNIQUE INDEX `full_name_UNIQUE` (`full_name` ASC) VISIBLE,
  UNIQUE INDEX `blood_result_UNIQUE` (`blood_result` ASC) VISIBLE,
  INDEX `DONOR_RECORD_ADDRESS_PK_FK_idx` (`address` ASC) VISIBLE,
  INDEX `DONOR_RECORD_BLOOD_BANK_PK_FK_idx` (`blood_bank` ASC) VISIBLE,
  INDEX `DONOR_RECORD_BLOOD_TYPE_PK_FK_idx` (`blood_type` ASC) VISIBLE,
  CONSTRAINT `DONOR_RECORD_BLOOD_TYPE_PK_FK`
    FOREIGN KEY (`blood_type`)
    REFERENCES `BloodDonationSystemDB`.`BloodType` (`blood_type_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `DONOR_DONOR_RECORD_FK`
    FOREIGN KEY (`donor`)
    REFERENCES `BloodDonationSystemDB`.`Donor` (`donor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `DONOR_RECORD_ADDRESS_FK`
    FOREIGN KEY (`address`)
    REFERENCES `BloodDonationSystemDB`.`Address` (`address_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `DONOR_RECORD_BLOOD_RESULT_FK`
    FOREIGN KEY (`blood_result`)
    REFERENCES `BloodDonationSystemDB`.`BloodResult` (`blood_result_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `DONOR_RECORD_DISEASE_VERIFICATION_FK`
    FOREIGN KEY (`disease_verification`)
    REFERENCES `BloodDonationSystemDB`.`DiseaseVerification` (`disease_verification_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `DONOR_RECORD_BLOOD_BANK_PK_FK`
    FOREIGN KEY (`blood_bank`)
    REFERENCES `BloodDonationSystemDB`.`BloodBank` (`blood_bank_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationSystemDB`.`MonitoringProcess`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationSystemDB`.`MonitoringProcess` ;

CREATE TABLE IF NOT EXISTS `BloodDonationSystemDB`.`MonitoringProcess` (
  `monitoring_process_id` INT(5) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`monitoring_process_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationSystemDB`.`Notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationSystemDB`.`Notifications` ;

CREATE TABLE IF NOT EXISTS `BloodDonationSystemDB`.`Notifications` (
  `notification_id` INT NOT NULL,
  `notifications_blood_bank_id` INT(5) NULL,
  `notifications_hospital_id` INT(5) NULL,
  `notifications_donor_id` INT(5) NULL,
  `notifications_laboratory_id` INT(5) NULL,
  `disease_verification_description` VARCHAR(60) NULL,
  `sent_description` VARCHAR(60) NULL,
  `received_description` VARCHAR(60) NULL,
  PRIMARY KEY (`notification_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationSystemDB`.`Manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationSystemDB`.`Manager` ;

CREATE TABLE IF NOT EXISTS `BloodDonationSystemDB`.`Manager` (
  `manager_id` INT NOT NULL,
  `blood_bank` INT(5) NOT NULL,
  `monitoring_process` INT(5) NOT NULL,
  `address` VARCHAR(60) NOT NULL,
  `donor_record` INT(5) NULL,
  `full_name` VARCHAR(60) NOT NULL,
  `total_notifications_received` INT NULL,
  `laboratory_notifications` INT(5) NULL DEFAULT 0,
  `notifications_received` INT NULL DEFAULT 0,
  `notifications_sent` INT NULL DEFAULT 0,
  PRIMARY KEY (`manager_id`, `blood_bank`, `monitoring_process`),
  INDEX `MANAGER_BLOOD_BANK_FK_idx` (`blood_bank` ASC) VISIBLE,
  INDEX `MANGER_DONOR_RECORD_FK_idx` (`donor_record` ASC) VISIBLE,
  UNIQUE INDEX `donor_record_UNIQUE` (`donor_record` ASC) VISIBLE,
  INDEX `MANAGER_MONITORING_PROCESS_FK_idx` (`monitoring_process` ASC) VISIBLE,
  INDEX `MANAGER_ADDRESS_FK_idx` (`address` ASC) VISIBLE,
  UNIQUE INDEX `full_name_UNIQUE` (`full_name` ASC) VISIBLE,
  INDEX `MANAGER_NOTIFICATION_SENT_FK_idx` (`notifications_sent` ASC) VISIBLE,
  INDEX `MANAGER_NOTIFICATION_RECEIVED_FK_idx` (`notifications_received` ASC) VISIBLE,
  INDEX `MANAGER_NOTIFICATION_LAB_FK_idx` (`laboratory_notifications` ASC) VISIBLE,
  CONSTRAINT `MANAGER_BLOOD_BANK_PK_FK`
    FOREIGN KEY (`blood_bank`)
    REFERENCES `BloodDonationSystemDB`.`BloodBank` (`blood_bank_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `MANGER_DONOR_RECORD_FK`
    FOREIGN KEY (`donor_record`)
    REFERENCES `BloodDonationSystemDB`.`DonorRecord` (`donor_record_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `MANAGER_MONITORING_PROCESS_PK_FK`
    FOREIGN KEY (`monitoring_process`)
    REFERENCES `BloodDonationSystemDB`.`MonitoringProcess` (`monitoring_process_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `MANAGER_ADDRESS_FK`
    FOREIGN KEY (`address`)
    REFERENCES `BloodDonationSystemDB`.`Address` (`address_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `MANAGER_NOTIFICATION_SENT_FK`
    FOREIGN KEY (`notifications_sent`)
    REFERENCES `BloodDonationSystemDB`.`Notifications` (`notification_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `MANAGER_NOTIFICATION_RECEIVED_FK`
    FOREIGN KEY (`notifications_received`)
    REFERENCES `BloodDonationSystemDB`.`Notifications` (`notification_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `MANAGER_NOTIFICATION_LAB_FK`
    FOREIGN KEY (`laboratory_notifications`)
    REFERENCES `BloodDonationSystemDB`.`Notifications` (`notification_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationSystemDB`.`Hospital`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationSystemDB`.`Hospital` ;

CREATE TABLE IF NOT EXISTS `BloodDonationSystemDB`.`Hospital` (
  `hospital_id` INT(5) NOT NULL,
  `address` VARCHAR(60) NOT NULL,
  `laboratory` INT(5) NULL,
  `donor_record` INT(5) NULL,
  `transfusion_doctor` INT(5) NULL,
  `blood_recipient_record` INT(5) NULL,
  `name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`hospital_id`),
  UNIQUE INDEX `donor_record_UNIQUE` (`donor_record` ASC) VISIBLE,
  UNIQUE INDEX `blood_recipient_record_UNIQUE` (`blood_recipient_record` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationSystemDB`.`Laboratory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationSystemDB`.`Laboratory` ;

CREATE TABLE IF NOT EXISTS `BloodDonationSystemDB`.`Laboratory` (
  `laboratory_id` INT(5) NOT NULL,
  `donor_record` INT(5) NULL,
  `blood_bank_notification` INT(5) NULL,
  `address` VARCHAR(60) NOT NULL,
  `hospital` INT(5) NULL,
  `disease_verification` INT(5) NOT NULL,
  `notification_sent` INT(5) NULL,
  `notification_received` INT(5) NULL,
  `name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`laboratory_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationSystemDB`.`BloodRecipient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationSystemDB`.`BloodRecipient` ;

CREATE TABLE IF NOT EXISTS `BloodDonationSystemDB`.`BloodRecipient` (
  `blood_recipient_id` INT(5) NOT NULL,
  `blood_recipient_record` INT(5) NULL,
  `blood_transfusion` INT(5) NULL,
  `transfusion_doctor` INT(5) NULL,
  PRIMARY KEY (`blood_recipient_id`),
  UNIQUE INDEX `blood_recipient_record_UNIQUE` (`blood_recipient_record` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationSystemDB`.`TransfusionDoctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationSystemDB`.`TransfusionDoctor` ;

CREATE TABLE IF NOT EXISTS `BloodDonationSystemDB`.`TransfusionDoctor` (
  `transfusion_doctor_id` INT(5) NOT NULL,
  `hospital` INT(5) NULL,
  `blood_recipient_record` INT(5) NULL,
  `donor_record` INT(5) NULL,
  `blood_transfusion` INT(5) NULL,
  `blood_result` INT(5) NULL,
  `full_name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`transfusion_doctor_id`),
  UNIQUE INDEX `full_name_UNIQUE` (`full_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationSystemDB`.`BloodRecipientRecord`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationSystemDB`.`BloodRecipientRecord` ;

CREATE TABLE IF NOT EXISTS `BloodDonationSystemDB`.`BloodRecipientRecord` (
  `blood_recipient_record_id` INT(5) NOT NULL,
  `address` VARCHAR(60) NOT NULL,
  `blood_type` INT(5) NOT NULL,
  `blood_recipient` INT(5) NOT NULL,
  `full_name` VARCHAR(60) NOT NULL,
  `blood_result` INT(5) NULL,
  `hospital` INT(5) NULL,
  `tranfusion_doctor` INT NULL,
  PRIMARY KEY (`blood_recipient_record_id`),
  UNIQUE INDEX `full_name_UNIQUE` (`full_name` ASC) VISIBLE,
  UNIQUE INDEX `blood_type_UNIQUE` (`blood_type` ASC) VISIBLE,
  UNIQUE INDEX `blood_result_UNIQUE` (`blood_result` ASC) VISIBLE,
  UNIQUE INDEX `blood_recipient_UNIQUE` (`blood_recipient` ASC) VISIBLE,
  INDEX `BLOOD_RECIPIENT_RECORD_HOSPITAL_PK_FK_idx` (`hospital` ASC) VISIBLE,
  INDEX `BLOOD_RECIPIENT_RECORD_TRANSFUSION_DOCTOR_PK_FK_idx` (`tranfusion_doctor` ASC) VISIBLE,
  CONSTRAINT `BLOOD_RECIPIENT_RECORD_ADDRESS_FK`
    FOREIGN KEY (`address`)
    REFERENCES `BloodDonationSystemDB`.`Address` (`address_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `BLOOD_RECIPIENT_RECORD_BLOOD_TYPE_FK`
    FOREIGN KEY (`blood_type`)
    REFERENCES `BloodDonationSystemDB`.`BloodType` (`blood_type_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `BLOOD_RECIPIENT_RECORD_BLOOD_RESULT_FK`
    FOREIGN KEY (`blood_result`)
    REFERENCES `BloodDonationSystemDB`.`BloodResult` (`blood_result_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `BLOOD_RECIPIENT_RECORD_BP_FK`
    FOREIGN KEY (`blood_recipient`)
    REFERENCES `BloodDonationSystemDB`.`BloodRecipient` (`blood_recipient_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `BLOOD_RECIPIENT_RECORD_HOSPITAL_FK`
    FOREIGN KEY (`hospital`)
    REFERENCES `BloodDonationSystemDB`.`Hospital` (`hospital_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `BLOOD_RECIPIENT_RECORD_TRANSFUSION_DOCTOR_FK`
    FOREIGN KEY (`tranfusion_doctor`)
    REFERENCES `BloodDonationSystemDB`.`TransfusionDoctor` (`transfusion_doctor_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationSystemDB`.`BloodTransfusion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationSystemDB`.`BloodTransfusion` ;

CREATE TABLE IF NOT EXISTS `BloodDonationSystemDB`.`BloodTransfusion` (
  `blood_transfusion_id` INT(5) NOT NULL,
  `transfusion_doctor` INT(5) NULL,
  `hospital` INT(5) NULL,
  `blood_recipient` INT(5) NULL,
  PRIMARY KEY (`blood_transfusion_id`),
  INDEX `BLOOD_TRANSFUSION_BP_FK_idx` (`blood_recipient` ASC) VISIBLE,
  UNIQUE INDEX `blood_recipient_UNIQUE` (`blood_recipient` ASC) VISIBLE,
  CONSTRAINT `BLOOD_TRANSFUSION_BP_FK`
    FOREIGN KEY (`blood_recipient`)
    REFERENCES `BloodDonationSystemDB`.`BloodRecipient` (`blood_recipient_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationSystemDB`.`PositiveResult`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationSystemDB`.`PositiveResult` ;

CREATE TABLE IF NOT EXISTS `BloodDonationSystemDB`.`PositiveResult` (
  `positive_result_id` INT(5) NOT NULL,
  `positive_result` TINYINT(1) NULL,
  `blood_result` INT(5) NULL,
  PRIMARY KEY (`positive_result_id`),
  INDEX `BR_POSITIVE_FK_idx` (`blood_result` ASC) VISIBLE,
  CONSTRAINT `BR_POSITIVE_FK`
    FOREIGN KEY (`blood_result`)
    REFERENCES `BloodDonationSystemDB`.`BloodResult` (`blood_result_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BloodDonationSystemDB`.`NegativeResult`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BloodDonationSystemDB`.`NegativeResult` ;

CREATE TABLE IF NOT EXISTS `BloodDonationSystemDB`.`NegativeResult` (
  `negative_result_id` INT(5) NOT NULL,
  `negative_result` TINYINT(1) NULL,
  `blood_result` INT(5) NULL,
  PRIMARY KEY (`negative_result_id`),
  INDEX `BR_NEGATIVE_FK_idx` (`blood_result` ASC) VISIBLE,
  CONSTRAINT `BR_NEGATIVE_FK`
    FOREIGN KEY (`blood_result`)
    REFERENCES `BloodDonationSystemDB`.`BloodResult` (`blood_result_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
